### ISSUE TITLE
Make the chat program work through NATs

### ISSUE THREAD

**Issue by GMart** [GMart/RSVoiP-CS374#3]
The chat part of the program could communicate using hole punching or another method, but is not high in the To-do list.

**Comment by ManualSearch** [comment]
Lol, cleaning up the old github account?

**Comment by GMart** [comment]
Yup! I still use it!

**Comment by ManualSearch** [comment]
I can see that! Hope things are going well. Have a nice week, and like... life, I guess? Lol.
